version: '3.10'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memes_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DATA_DIR: /var/lib/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - ${PWD}/.localstack:/custom_tmp/localstack
    command: sh -c "rm -rf /tmp/localstack/* && localstack start"
    networks:
      - app-network

  memes_app:
    build: .
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    ports:
      - "8000:8000"
    depends_on:
      - db
      - localstack
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: "db"
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      S3_ENDPOINT_URL: http://localstack:4566
      S3_ACCESS_KEY: test
      S3_SECRET_KEY: test
      S3_BUCKET_NAME: memes
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  .localstack:
